# Generated by Django 3.2.7 on 2022-10-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.newuser'),
        ),
    ]
