# Generated by Django 3.2.7 on 2022-10-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainings',
        ),
        migrations.AddField(
            model_name='course',
            name='trainings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.training'),
        ),
    ]
