# Generated by Django 3.2.7 on 2022-10-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resource_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='patient',
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resource'),
        ),
    ]
