# Generated by Django 3.2.7 on 2022-10-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='user',
            new_name='supervisor',
        ),
    ]
