# Generated by Django 3.2.7 on 2022-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_user_audio_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='data',
        ),
        migrations.AddField(
            model_name='audio',
            name='audioid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
